package com.example.quezgame;

public class quezData {

    String[] questions = {
            "Who is the Father of our Nation?",
            "Who was the first President of India?",
            "Who is known as the Father of the Indian Constitution?",
            "Which is the most sensitive organ in our body?",
            "Giddha is the folk dance of which state?",
            "Who was the first Prime Minister of India?",
            "Which is the heavier metal of these two? Gold or Silver?",
            "Who invented the computer?",
            "How many Kilobytes are equal to 1 Megabyte (MB)?",
            "Which component is known as the 'brain' of a computer?",
            "computer is an ?",
            "who is the father of computer",
            "in which year java is Discovered?",
            "java is :",
            "java is also use in?",
            "name first programming language of computer?",
            "how many data types use in computer programming?",
            "int data type is use for?",
            "float is used for the?",
            "array is the?",
            "collection of character is known aas?",
            "abstraction method have?",
            "name of inheritance which support interface?",
            "array index is start from the ?",
            "what is exception?",
            "what is encapsulation",
            "super keyword is use for refer the?",
            "method Overloding have?",
            "method Overriding  have?",
            "how many types exception occur in java",
            "polymorphism is?",
            "for loop have the?",
            "while loop are going ?",
            "do while loop run Atleast?",
            "interface achieve the?",
            "final keyword is used to indicate the",
            "abstraction not support the?",
            "Compile time polymorphism is also known as?",
            "Linear layout is?",
            "Relative layout is?",
            "constraint layout determine the position of?",
            "drawbel  is help us to? ",
            "which folder is used for copy and paste an image into?",
            " Which component property should be changed to a name that is specific of the components use",
            "Which is correct for using any image with the name transtation?",
            "which android studio file is most  of the app coding done?",
            "wap stands for?",
            "In android mini activities is known as?",
            "in which of the following is the android studio framework provide",
            "on what android is android web browser-based?"





    };

    String[] optionA = {
            "Jawaharlal Nehru",
            "Dr.B.R. Ambedkar",
            "Mahatma Gandhi",
            "Eyes",
            "Gujarat",
            "Jawaharlal Nehru",
            "Gold",
            "Bill Gates",
            "512 Kilobytes",
            "CPU",
            "electronic machine",
            "bill gates",
            "1990",
            "program",
            "cloud",
            "java",
            "5",
            "decimal values",
            "integer values",
            "character",
            "string",
            "body",
            "single",
            "6",
            "error",
            "data hiding",
            "subclass",
            "same argument",
            "different class",
            "8",
            "have'nt forms",
            "start and end point",
            "1 time",
            "2 time",
            "no abstraction",
            "variables",
            "multiple inheritance",
            "dynamic polymorphism",
            "A view that align all children in single direction",
            "have no position",
            "layout",
            "set the app size",
            "layout",
            "text ",
            "@drawable/trsition",
            "Main activity.java",
            "Wireless application protocol",
            "adapter",
            "zip file",
            "safari"





    };

    String[] optionB = {
            "Mahatma Gandhi",
            "Jawaharlal Nehru",
            "Subhash Chandra Bose",
            "Ears",
            "Rajasthan",
            "Indira Gandhi",
            "Silver",
            "Steve Jobs",
            "1024 Kilobytes",
            "RAM",
            "mechanical machine",
            "charles babes",
            "1996",
            "device",
            "web",
            "C",
            "2",
            "integer value",
            "String value",
            "same data type",
            "array",
            "no body",
            "multilevel",
            "1",
            "abnormal condition",
            "data showing",
            "only parent class",
            "abstraction",
            "same class ",
            "1",
            "have the same form",
            "only start point",
            "2 times",
            "1 time",
            "half abstraction",
            "method",
            "single inheritance",
            "overiding",
            "A view that align all children in different direction",
            "have position",
            "UI",
            "set page size",
            "resources",
            "id",
            "android src",
            "Activity main xml",
            "wireless application program",
            "activity",
            "jar file",
            "firefox"




    };

    String[] optionC = {
            "Subhash Chandra Bose",
            "Dr. Rajendra Prasad",
            "Dr.B.R. Ambedkar",
            "Nose",
            "Punjab",
            "Atal Bihari Vajpayee",
            "They have the same weight",
            "Alan Turing",
            "2048 Kilobytes",
            "CPU",
            "electrical device",
            "james harvi",
            "1991",
            "languge",
            "android app",
            "C++",
            "7",
            "automatic value",
            "user undefined",
            "differt data type",
            "float",
            "abtraction",
            "multiple",
            "0",
            "bug",
            "data internet",
            "subclass only",
            "same name",
            "different argument",
            "2",
            "condition of occuring in several different forms",
            "only end point",
            "3 times",
            "4 time",
            "100% abstraction",
            "class",
            "multilevel inheritance",
            "static polymorphism",
            "A view that align all children in any direction",
            "A view that display child view in realtive position",
            "layout",
            "set icones",
            "drawel",
            "content",
            "android  src=@drawable/trasition",
            "android main",
            "wireless application port",
            "fragment",
            "object file",
            "open source Webkit"


    };

    String[] optionD = {
            "Sardar Vallabhbhai Patel",
            "Indira Gandhi",
            "Jawaharlal Nehru",
            "Skin",
            "Kerala",
            "Narendra Modi",
            "It depends on the quantity",
            "Charles Babbage",
            "4096 Kilobytes",
            "Hard Drive",
            "chemical machine",
            "einstein",
            "1997",
            "history",
            "digital ",
            "apex",
            "none",
            "direct value",
            "undefined",
            "int data type",
            "char",
            "none",
            "hybrid",
            "2",
            "wrong",
            "database",
            "parent class of the subclass",
            "different name",
            "different name",
            "3",
            "none",
            "no point",
            "infinity times",
            "3 times",
            "20% abstraction",
            "varable,method,class",
            "hybrid inheritance",
            "none",
            "All  of these",
            "all of these",
            "page",
            "A view that display child view in realtive position",
            "organize the navigation inside the app",
            "java",
            "description",
            "none",
            "all",
            "wireless application portal",
            "none",
            "exe file",



    };

    String[] correctAnswers = {
            "Mahatma Gandhi",
            "Dr. Rajendra Prasad",
            "Dr.B.R. Ambedkar",
            "Skin",
            "Punjab",
            "Jawaharlal Nehru",
            "Gold",
            "Charles Babbage",
            "1024 Kilobytes",
            "CPU",
            "electronic machine",
            "charles babes",
            "1991",
            "programmin language",
            "android app",
            "c",
            "2",
            "integer value",
            "decimaal value",
            "same data type",
            "string",
            "have no body",
            "multiple",
            "0",
            "abnormal condition",
            "data hiding",
            "parent class  of the subclass",
            "same name",
            "different class",
            "2",
            "condition of occuring in several different forms",
            "start and end point",
            "infinity times",
            "1 time",
            "100% abstration",
            "variable, method , class",
            "multiple inheritance",
            "static polymorphism",
            "A view that align all children in different direction",
            "A view that display child view in realtive position",
            "UI",
            "organize the navigation inside the app",
            "drawel",
            "id",
            "android src=@drawable/trsanisition",
            "Mainctivity.java",
            "wireless application protocol",
            "fragment",
            "jar file",
            "open source webkit"







    };


}
